on:
  push:
    branches:
      - main
      - dev

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: ğŸ› Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: ğŸ— Setup NodeJS
        uses: actions/setup-node@v4
        with: { node-version-file: .node-version, cache: npm }
      - name: ğŸ“¦ Install dependencies
        run: npm ci
      - name: ğŸ” Run check
        run: npm run lint
      - name: ğŸ— Build
        run: npm run build
      - name: ğŸš€ Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        env:
          CF_PROJECT: ${{ vars.CLOUDFLARE_PROJECT_ID }}
          CF_ENVIRONMENT: ${{ github.ref_name == 'main' && 'production' || 'preview' }}
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: pages deploy out --upload-source-maps --project-name ${{ vars.CLOUDFLARE_PROJECT_ID }}
